# Change these first
owner: applabomatic # Your GitHub organization or username, where this repository lives
repo: siteuptimely # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Reddit
    url: https://www.reddit.com
#  - name: Test Broken Site
#    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.siteuptimely.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SiteUptimely
  introTitle: "[**SiteUptimely**](https://siteuptimely.com/) is a trusted website monitoring tool that helps keep track of your website's downtime, performance, and domain health."
  introMessage: It is used by thousands of websites all over the world.
  navbar:
    - title: Home
      href: https://siteuptimely.com/
    - title: Status
      href: /
  theme: ocean
# light, dark, night, ocean
  robotsText: "User-agent: * \n Disallow: /"
  
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

i18n:
  footer: Powered by [SiteUptimely](https://siteuptimely.com/)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
